language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry php artisan key:generate
  - travis_retry npm install
  - travis_retry npm install -g bower
  - travis_retry bower install

before_script:
  - travis_retry gulp --production

script: vendor/bin/phpunit
